#!/usr/bin/env bash

# Profile for "bacon": my main macOS workstation.
# --------------------------------------------------------------------------------------------------

export SYMLINKS=(
  "zsh/.zshenv"
  "tmux/tmux.conf .tmux.conf"
)

export TOPICS=(
  common
  homebrew

  coc
  fnm
  macos
  npm
  nvim
  phpbrew
  python
  ruby
  ssh
  tmux
  zsh
)
