#!/usr/bin/env bash

#          __      _.._
#       .-'__`-._.'.--.'.__.,
#      /--'  '-._.'    '-._./
#     /__.--._.--._.'``-.__/
#     '._.-'-._.-._.-''-..'
#
# Profile for "bacon": my main macOS workstation.
# --------------------------------------------------------------------------------------------------

export SYMLINKS=(
  "zsh/.zshenv"
  "tmux/tmux.conf .tmux.conf"
)

export TOPICS=(
  homebrew
  symlink

  fnm
  macos
  npm
  python
  ruby
  ssh
  tmux
)
